name: bgg_api
description:
  Board Game Geek XML API client (version 2)
  This package was inspired by bgg.dart package, which works with first version of BGG API.
version: 0.7.0
repository: https://github.com/bartektartanus/bgg_api

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  xml: ^6.5.0
  html_unescape: ^2.0.0
  http: ^1.2.1
  meta: ^1.12.0

dev_dependencies:
  analyzer: ^6.4.1
  coverage: ^1.7.2
  pedantic: ^1.11.1
  test: ^1.25.2
